version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  mongo:
    restart: always
    ports:
      - 27017:27017
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    environment:
      - MONGO_DB_CONNECTION_STRING=mongodb://mongo:27017/app
    networks:
      - app_network
      - express-mongo

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  express-mongo:
  app_network:
    external: true
